<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- torso parameters -->
    <xacro:property name="torso_height" value="0.3"/>
    <xacro:property name="torso_width" value="0.4"/>
    <xacro:property name="torso_thickness" value="0.19"/>
    <xacro:property name="torso_back_offset" value="0.02"/>

    <xacro:include filename="$(find freddy_base_description)/urdf/common.xacro" />
    <xacro:include filename="$(find freddy_base_description)/urdf/freddy_base.urdf.xacro" />

    <xacro:macro name="freddy_torso" params="name parent *origin use_gpu_2d_laser:=true">
        <!-- TORSO -->
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="${name}_link" />
        </joint>

        <link name="${name}_link">
            <visual>
                <origin xyz="${-base_size_x/2 + torso_back_offset + torso_thickness/2} 0 ${wheel_slit_height + base_size_z + torso_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${torso_thickness} ${torso_width} ${torso_height}" />
                </geometry>
                <material name="DarkGrey"/>
            </visual>

            <!-- torso collision -->
            <collision>
                <origin xyz="${-base_size_x/2 + torso_back_offset + torso_thickness/2} 0 ${wheel_slit_height + base_size_z + torso_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${torso_thickness} ${torso_width} ${torso_height}" />
                </geometry>
            </collision>

            <xacro:cuboid_inertia mass="${base_mass}" length="${base_size_x}"
                                  breadth="${base_size_y}" height="${base_size_z}"/>
        </link>

        <gazebo reference="${name}_link">
            <material>Gazebo/RustySteel</material>
        </gazebo>

    </xacro:macro>
</robot>
