<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- simplified box collision geometry for base -->
    <xacro:property name="robot_name" value="freddy"/>

    <xacro:property name="base_size_x" value="0.635"/>
    <xacro:property name="base_size_y" value="0.582"/>
    <xacro:property name="base_size_z_bottom" value="0.12"/>
    <xacro:property name="wheel_slit_height" value="0.1"/>
    <xacro:property name="laser_slit_height" value="0.05"/>
    <xacro:property name="base_size_z_top" value="0.1"/>
    <xacro:property name="base_size_z" value="${base_size_z_bottom + laser_slit_height + base_size_z_top}"/>
    <xacro:property name="base_mass" value="40.0"/>

    <!-- <xacro:include filename="$(find freddy_base_description)/urdf/sensors/hokuyo.urdf.xacro" /> -->
    <xacro:include filename="$(find freddy_base_description)/urdf/kelo_wheel_gz.urdf.xacro" />

    <xacro:macro name="freddy_base" params="name parent *origin use_gpu_2d_laser:=true">
        <!-- HOLONOMIC DRIVE PLUGIN -->
        <!-- <gazebo>
            <plugin name="gazebo_ros_planar_move" filename="libgazebo_ros_planar_move.so">
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryRate>20.0</odometryRate>
            <robotBaseFrame>${parent}</robotBaseFrame>
            </plugin>
        </gazebo> -->

        <!-- BASE -->
        <joint name="${name}_joint" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="${name}_link" />
        </joint>

        <link name="${name}_link">
            <visual>
                <origin xyz="0 0 ${wheel_slit_height + base_size_z_bottom/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z_bottom}" />
                </geometry>
                <material name="DarkGrey"/>
            </visual>
            <visual>
                <origin xyz="0 0 ${wheel_slit_height + base_size_z_bottom + laser_slit_height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_size_x*0.7} ${base_size_y*0.7} ${laser_slit_height}" />
                </geometry>
                <material name="DarkGrey"/>
            </visual>
            <visual>
                <origin xyz="0 0 ${wheel_slit_height + base_size_z_bottom + laser_slit_height + base_size_z_top/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z_top}" />
                </geometry>
                <material name="DarkGrey"/>
            </visual>

            <!-- base bottom collisions -->
            <collision>
                <origin xyz="0 0 ${wheel_slit_height + base_size_z_bottom/2}" rpy="0 0 0.0"/>
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z_bottom}" />
                </geometry>
            </collision>

            <!-- base top collisions -->
            <collision>
                <origin xyz="0 0 ${wheel_slit_height + base_size_z_bottom + laser_slit_height + base_size_z_top/2}" rpy="0 0 0.0"/>
                <geometry>
                    <box size="${base_size_x} ${base_size_y} ${base_size_z_top}" />
                </geometry>
            </collision>

            <xacro:cuboid_inertia mass="${base_mass}" length="${base_size_x}"
                                  breadth="${base_size_y}" height="${base_size_z}"/>
        </link>

        <gazebo reference="${name}_link">
            <material>Gazebo/RustySteel</material>
        </gazebo>


        <!-- WHEELS -->
        <xacro:kelo_wheel name="left_front_wheel" parent="${name}_link" material_name="Black">
            <origin xyz="${base_size_x*0.5 - wheel_radius}
                         ${base_size_y*0.5 - wheel_radius}
                         ${wheel_radius}"
                    rpy="0 0 0"/>
        </xacro:kelo_wheel>
        <xacro:kelo_wheel name="right_front_wheel" parent="${name}_link" material_name="Black">
            <origin xyz="${base_size_x*0.5 - wheel_radius}
                         ${-(base_size_y*0.5 - wheel_radius)}
                         ${wheel_radius}"
                    rpy="0 0 0"/>
        </xacro:kelo_wheel>
        <xacro:kelo_wheel name="left_back_wheel" parent="${name}_link" material_name="Black">
            <origin xyz="${-(base_size_x*0.5 - wheel_radius)}
                         ${base_size_y*0.5 - wheel_radius}
                         ${wheel_radius}"
                    rpy="0 0 0"/>
        </xacro:kelo_wheel>
        <xacro:kelo_wheel name="right_back_wheel" parent="${name}_link" material_name="Black">
            <origin xyz="${-(base_size_x*0.5 - wheel_radius)}
                         ${-(base_size_y*0.5 - wheel_radius)}
                         ${wheel_radius}"
                    rpy="0 0 0"/>
        </xacro:kelo_wheel>


        <!-- HOKUYO LASER -->
        <!-- <xacro:if value="$(arg load_sensors)">
        <xacro:hokuyo name="base_laser_front" parent="${name}_link"
                           topic="/${robot_name}/base_scan_front" use_gpu="${use_gpu_2d_laser}">
            <origin xyz="0.26 -0.24 0.25" rpy="${pi} 0 ${-pi/4}"/>
        </xacro:hokuyo>

        <xacro:hokuyo name="base_laser_back" parent="${name}_link"
                           topic="/${robot_name}/base_scan_back" use_gpu="${use_gpu_2d_laser}">
            <origin xyz="-0.26 0.24 0.25" rpy="${pi} 0 ${3*pi/4}"/>
        </xacro:hokuyo>
        </xacro:if> -->

        <!-- VELOCITY CONTROL GZ PLUGIN -->
        <!-- <xacro:if value="$(arg sim_gz)"> -->
        <!-- <gazebo>
            <plugin
                filename="gz-sim-velocity-control-system"
                name="gz::sim::systems::VelocityControl">
            modified
            <topic>cmd_vel</topic>
            <link_name>base_link</link_name>
            gz added
            </plugin>
        </gazebo> -->
        <!-- </xacro:if> -->

    </xacro:macro>
</robot>
